In [3]:
import math 
def sigmoid(x):
    return 1/(1+ math.exp(-1*x))

In [4]:
sigmoid(100)

1.0

In [5]:
sigmoid(1)

0.7310585786300049

In [6]:
sigmoid(-56)

4.780892883885469e-25

In [7]:
sigmoid(0.5)

0.6224593312018546

In [8]:
def tanh(x):
    return (math.exp(x) - math.exp(-x))/(math.exp(x)+math.exp(-x))

In [9]:
tanh(-56)

-1.0

In [10]:
tanh(50)

1.0

In [11]:
tanh(1)

0.7615941559557649

In [12]:
def relu(x):
    return max(0,x)


In [13]:
relu(-7)

0

In [14]:
relu(9)

9

In [15]:
relu(-100)

0

In [16]:
def leaky_relu(x):
    return max(0.1*x, x)


In [17]:
leaky_relu(100)

100

In [18]:
leaky_relu(-100)

-10.0

In [19]:
leaky_relu(0)

0.0

In [20]:
import numpy as np


In [21]:
revenue = np.array([[180,200,220],[24,36,40],[12,18,20]])
expenses =  np.array([[80,90,100],[10,16,20],[8,10,10]])

In [22]:
profit = revenue - expenses

In [23]:
profit

array([[100, 110, 120],
       [ 14,  20,  20],
       [  4,   8,  10]])

In [24]:
pric_per_unit = np.array([1000,400,1200])
units = np.array([[30,40,50],[5,10,15],[2,5,7]])


In [25]:
pric_per_unit*units

array([[30000, 16000, 60000],
       [ 5000,  4000, 18000],
       [ 2000,  2000,  8400]])

In [26]:
np.dot(pric_per_unit , units)

array([34400, 50000, 64400])

In [27]:
y_predicted = np.array([1,1,0,0,1])
y_true = np.array([0.30 ,0.7 ,1,0,0.5])

In [28]:
import math
def mae(y_true ,y_pred):
    total_error =0
    n = len(y_true)
    for yt,yp in zip(y_true ,y_pred):
        total_error += abs(yt -yp)
    return total_error/n

In [29]:
mae(y_true , y_predicted)

0.5

In [30]:
np.mean(np.abs(y_true - y_predicted))

0.5

In [31]:
np.mean(np.square(np.abs(y_true-y_predicted)))

0.366

In [32]:
def mse(y_true , y_pred):
    total_error = 0
    for yt ,yp in zip(y_true ,y_pred):
        total_error+= (yt - yp)**2
    return total_error/len(y_true)
        

In [33]:
mse(y_true ,y_predicted)


0.366

In [34]:
np.log(0)

C:\Users\hp\AppData\Local\Temp\ipykernel_10120\2933082444.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(0)


-inf

In [35]:
np.log([0.0000000001])

array([-23.02585093])

In [36]:
epsilon = 1e-15


In [37]:
y_predicted_new =  [max(i,epsilon) for i in y_predicted]
y_predicted_new

[1, 1, 1e-15, 1e-15, 1]

In [38]:
y_predicted_new = [min(i,1-epsilon)for i in y_predicted_new]
y_predicted_new

[0.999999999999999, 0.999999999999999, 1e-15, 1e-15, 0.999999999999999]

In [39]:
np.log(y_predicted)

C:\Users\hp\AppData\Local\Temp\ipykernel_10120\815880036.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(y_predicted)


array([  0.,   0., -inf, -inf,   0.])

In [40]:
-np.mean(y_true*np.log(y_predicted_new) + (1-y_true)*np.log(1-y_predicted_new))

TypeError: unsupported operand type(s) for -: 'int' and 'list'

In [ ]:
def log_loss(y_true ,y_predicted):
    epsilon = 1e-15
    y_predicted_new =  [max(i,epsilon) for i in y_predicted]
    y_predicted_new = [min(i,1-epsilon)for i in y_predicted_new]
    y_predicted_new = np.array(y_predicted_new)
    return -np.mean(y_true*np.log(y_predicted_new) + (1-y_true)*np.log(1-y_predicted_new))  
    

In [ ]:
log_loss(y_true , y_predicted)

17.2696280766844