In [1]:
import numpy as np

In [2]:
a= np.array([1,2,3])

In [3]:
print(a)

[1 2 3]


In [4]:
b= np.array([[9,8,7],[6,5,4]])

In [5]:
print(b)

[[9 8 7]
 [6 5 4]]


In [6]:
a.ndim

1

In [7]:
b.ndim

2

In [8]:
a.shape

(3,)

In [16]:
#get shape
b.shape

(2, 3)

In [11]:
a.dtype

dtype('int32')

In [14]:
#get type

b.dtype

dtype('int32')

In [17]:
#get size
a.itemsize

4

In [18]:
#get total size
a.size

3

In [19]:
a.nbytes

12

In [20]:
x = np.array([12,3,45] ,dtype='int32')

In [21]:
x

array([12,  3, 45])

# Accessing/Changing specific elements  , rows ,columns etc

In [22]:
a = np.array([[1,2,3,4,5,6],[7,8,9,10,11,12]])
print(a)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [24]:
a.shape

(2, 6)

In [28]:
#get a specific element
a[1,4]

11

In [29]:
a[1,-2]

11

In [32]:
#get a specific row
a[0 ,:]

array([1, 2, 3, 4, 5, 6])

In [33]:
#get a specific column
a[: , 0]

array([1, 7])

In [34]:
a[0,1:6:2]

array([2, 4, 6])

In [35]:
a[1,5] =32

In [36]:
a

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 32]])

In [38]:
a[: ,2] = 5

In [39]:
a

array([[ 1,  2,  5,  4,  5,  6],
       [ 7,  8,  5, 10, 11, 32]])

In [40]:
a[:,2] = [3,9]

In [41]:
a

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 32]])

In [42]:
b= np.array([[[1,2] , [3,4]] , [[5,6],[7,8]]])

In [43]:
b

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [45]:
#get specific element
b[0,1 ,1]

4

In [47]:
b[: , 1 ,:]

array([[3, 4],
       [7, 8]])

In [48]:
b[:,1,:] = [[9,9] ,[8,8]]

In [49]:
b

array([[[1, 2],
        [9, 9]],

       [[5, 6],
        [8, 8]]])

# Initializing different types of array

In [52]:
a = np.zeros((2,3))

In [53]:
a

array([[0., 0., 0.],
       [0., 0., 0.]])

In [54]:
a = np.zeros((2,3 ,5))

In [55]:
a

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [56]:
a = np.zeros((2,3 ,5,2))

In [57]:
a

array([[[[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]]]])

In [58]:
#all 1's matrix

In [59]:
np.ones((1,3) ,dtype='int32')

array([[1, 1, 1]])

In [61]:
np.full((2,2) , 99 , dtype='float32')

array([[99., 99.],
       [99., 99.]], dtype=float32)

In [64]:
#any other number full like
np.full_like(a ,4)

array([[[[4., 4.],
         [4., 4.],
         [4., 4.],
         [4., 4.],
         [4., 4.]],

        [[4., 4.],
         [4., 4.],
         [4., 4.],
         [4., 4.],
         [4., 4.]],

        [[4., 4.],
         [4., 4.],
         [4., 4.],
         [4., 4.],
         [4., 4.]]],


       [[[4., 4.],
         [4., 4.],
         [4., 4.],
         [4., 4.],
         [4., 4.]],

        [[4., 4.],
         [4., 4.],
         [4., 4.],
         [4., 4.],
         [4., 4.]],

        [[4., 4.],
         [4., 4.],
         [4., 4.],
         [4., 4.],
         [4., 4.]]]])

In [69]:
#random decimal numbers
a = np.random.rand(4,4)

In [70]:
a

array([[0.64113739, 0.61064394, 0.79739249, 0.20329813],
       [0.24873673, 0.14595236, 0.61522738, 0.33700115],
       [0.33304724, 0.49437546, 0.04452313, 0.94598979],
       [0.51313005, 0.94280103, 0.64239482, 0.93731965]])

In [72]:
np.random.random_sample(b.shape)

array([[[0.60403402, 0.62603018],
        [0.27096074, 0.7296081 ]],

       [[0.24603479, 0.75734541],
        [0.72655677, 0.85038531]]])

In [83]:
#random integer values
np.random.randint(5,11,size=(2,2))

array([[ 6,  7],
       [ 5, 10]])

In [84]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [85]:
arr=np.array([1,2,3])
r1 = np.repeat(arr ,3)
r1

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [88]:
arr=np.array([[1,2,3]])
r1 = np.repeat(arr ,3 ,axis=0)
r1

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [89]:
r1 = np.repeat(arr ,3 ,axis=1)
r1

array([[1, 1, 1, 2, 2, 2, 3, 3, 3]])

In [96]:
op = np.ones((5,5))
o = np.zeros((3,3))

o[1,1] =9
o
op[1:4 ,1:4] = o
op

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 9., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

# Be careful when copying arrays!!

In [99]:
a = np.array([1,2,3])
b=a
b[0]=100

print(b)
print(b)

[100   2   3]
[100   2   3]


In [100]:
a[0]=1

In [101]:
a

array([1, 2, 3])

In [102]:
b

array([1, 2, 3])

In [103]:
b = a.copy()

In [104]:
b

array([1, 2, 3])

In [106]:
b[0]=100
b

array([100,   2,   3])

In [107]:
a

array([1, 2, 3])

In [108]:
a+2

array([3, 4, 5])

In [109]:
a-2

array([-1,  0,  1])

In [110]:
a*2

array([2, 4, 6])

In [111]:
a/2

array([0.5, 1. , 1.5])

In [112]:
a+=2

In [113]:
a

array([3, 4, 5])

In [114]:
a**2

array([ 9, 16, 25])

In [115]:
np.sin(a)

array([ 0.14112001, -0.7568025 , -0.95892427])

In [116]:
np.cos(a)

array([-0.9899925 , -0.65364362,  0.28366219])

# Linear Algebra

In [118]:
a = np.full((2,3) ,2)
a

array([[2, 2, 2],
       [2, 2, 2]])

In [119]:
b= np.ones((3,2))

In [120]:
b

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [121]:
np.matmul(a ,b)

array([[6., 6.],
       [6., 6.]])

In [123]:
#find the determinant
c = np.identity(3)
np.linalg.det(c)

1.0

# Statistics

In [124]:
s = np.array([[1,2,3] ,[4,5,6]])

In [126]:
np.min(s ,axis=1)

array([1, 4])

In [127]:
np.max(s)

6

In [128]:
np.sum(s)

21

# Reorganizing arrays

In [129]:
before= np.array([[1,2,3,4] ,[5,6,7,8]])

In [130]:
before

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [131]:
after = before.reshape((4,2))

In [132]:
after

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [133]:
after = before.reshape((2,2,2))

In [134]:
after

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [136]:
#vertical stacking vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])
np.hstack([v1,v2])


array([1, 2, 3, 4, 5, 6, 7, 8])

In [137]:
np.vstack([v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

# Miscellaneous

In [140]:
filedata = np.genfromtxt('data.txt' , delimiter=',')

In [142]:
filedata = filedata.astype('int32')
filedata

array([[  1,  13,  21,  11, 196,  75,   4,   3,  34,   6,   7,   8,   0,
          1,   2,   3,   4,   5],
       [  3,  42,  12,  33, 766,  75,   4,  55,   6,   4,   3,   4,   5,
          6,   7,   0,  11,  12],
       [  1,  22,  33,  11, 999,  11,   2,   1,  78,   0,   1,   2,   9,
          8,   7,   1,  76,  88]])

#Boolean MAsking and Advanced Indexing 

In [143]:
filedata>50

array([[False, False, False, False,  True,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [144]:
filedata[filedata>50]

array([196,  75, 766,  75,  55, 999,  78,  76,  88])

In [146]:
#you can index with a list in numpy
a=np.array([1,2,3,4,5,6,7,8])
a[[1,2,7]]



array([2, 3, 8])

In [147]:
np.any(filedata>50 , axis=0)

array([False, False, False, False,  True,  True, False,  True,  True,
       False, False, False, False, False, False, False,  True,  True])

In [148]:
np.all(filedata>50 , axis=0)

array([False, False, False, False,  True, False, False, False, False,
       False, False, False, False, False, False, False, False, False])

In [154]:
a = np.linspace(1,25 , num=25 ,dtype='int32')

In [155]:
a.shape

(25,)

In [156]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25])

In [159]:
a = a.reshape((5,5))

In [160]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [161]:
a[2:4 ,:2]

array([[11, 12],
       [16, 17]])

In [162]:
a[[0,1,2,3] ,[1,2,3,4]]

array([ 2,  8, 14, 20])

In [166]:
a[[0,4] ,3:]

array([[ 4,  5],
       [24, 25]])